### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Thegameinglemon10** [SiskSjet/SmarterSuit#7]
Not sure if this mod is the cause, but this keeps happening and it keeps mentioning this mod in the final error.

```
2022-10-27 22:35:13.719 - Thread:   1 ->  Exception occurred: System.NullReferenceException: Object reference not set to an instance of an object.
   at Sandbox.Game.Entities.Character.MyCharacter.VRage.Game.ModAPI.Interfaces.IMyControllableEntity.get_EnabledHelmet()
   at Sisk.SmarterSuit.Mod.OnBeforeDamage(Object target, MyDamageInformation& info)
   at Sandbox.Game.GameSystems.MyDamageSystem.RaiseBeforeDamageAppliedIntenal(Object target, MyDamageInformation& info)
   at Sandbox.Game.Entities.Character.MyCharacter.DoDamage(Single damage, MyStringHash damageType, Boolean updateSync, Int64 attackerId)
   at Sandbox.Game.Entities.Character.MyCharacter.VRage.Game.ModAPI.Interfaces.IMyDestroyableObject.DoDamage(Single damage, MyStringHash damageType, Boolean sync, Nullable`1 hitInfo, Int64 attackerId, Int64 realHitEntityId, Boolean shouldDetonateAmmo)
   at Jakaria.Components.WaterPhysicsComponentCharacter.UpdateAfter60()
   at System.Action.Invoke()
   at Jakaria.SessionComponents.WaterModComponent.UpdateAfterSimulation()
   at System.Action.Invoke()
   at Jakaria.Session.UpdateAfterSimulation()
   at Sandbox.Game.World.MySession.UpdateComponents()
   at Sandbox.Game.World.MySession.Update(MyTimeSpan updateTime)
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
2022-10-27 22:35:13.721 - Thread:   1 ->  Showing message
2022-10-27 22:35:19.808 - Thread:   1 ->  
================================== CRASH INFO ==================================
AppVersion: 01_201_013
GameName: Space Engineers
IsOutOfMemory: False
IsGPU: False
IsNative: False
IsTask: False
IsExperimental: True
ProcessRunTime: 11149
PCUCount: 2606
IsHang: False
GCMemory: 3278
GCMemoryAllocated: 3278
HWAvailableMemory: 5271
ProcessPrivateMemory: 15928
AnalyticId: SE
================================== OFNI HSARC ==================================

2022-10-27 22:35:19.809 - Thread:   1 ->  Log Closed
```

**Comment by Thegameinglemon10** [comment]
Nevermind, just got the crash again even after disabling the mod.
